"""Single source of the backend version at runtime.

Generated by ``scripts/sync-version.mjs`` from the root ``package.json``. Do not
edit by hand — CI fails if this drifts from the authoritative version.

This exists instead of ``importlib.metadata.version()`` because PyInstaller does
not reliably carry dist-info into a frozen build, and a ``/health`` response
reporting the literal string ``unknown`` is useless in exactly the situation
where you would ask a user to read it back.
"""

__version__ = "0.1.0"
