"""Shared-secret authentication.

Tech.md §4.2: bound to ``127.0.0.1`` on a random free port, with a token
generated by Tauri and required on every request. That prevents any other local
process — including a browser tab the user has open — from driving the render
pipeline.

Q43: **no exemptions**, ``/health`` included. It leaks ``workspace_path`` and
therefore a username, so it should not be open regardless of how convenient an
unauthenticated liveness probe would be.

The debugging need that argues for an exemption is met instead by the dev token
file (see ``devtoken.py``): curl-able in a ``--dev`` build, absent in a packaged
one, never in the rolling log.
"""

import logging
import secrets
from typing import Annotated

from fastapi import Depends, Header, Request, status

from outreachos_backend.core.errors import ApiError, ApiErrorCode

__all__ = ["RequireToken", "require_token"]

log = logging.getLogger(__name__)

_SCHEME = "bearer"


async def require_token(
    request: Request,
    authorization: Annotated[str | None, Header()] = None,
) -> None:
    """Reject anything without the shared secret.

    Q43: ``secrets.compare_digest``, and a failed compare logs the request path
    but **never the presented value**. Logging what an attacker sent puts a
    near-miss of the real token into a file the user is asked to send us.
    """
    expected: str = request.app.state.runtime.token

    scheme, _, presented = (authorization or "").partition(" ")

    if scheme.lower() != _SCHEME or not presented:
        log.warning("missing or malformed Authorization header for %s", request.url.path)
        raise ApiError(
            ApiErrorCode.UNAUTHORIZED,
            "This request needs an Authorization: Bearer header.",
            status_code=status.HTTP_401_UNAUTHORIZED,
        )

    if not secrets.compare_digest(presented, expected):
        log.warning("rejected a request to %s: token mismatch", request.url.path)
        raise ApiError(
            ApiErrorCode.UNAUTHORIZED,
            "The shared secret did not match.",
            status_code=status.HTTP_401_UNAUTHORIZED,
        )


RequireToken = Depends(require_token)
"""Applied once, at the router level, so a new endpoint is authenticated by
default rather than by remembering to decorate it."""
