/**
 * Generated from the backend's OpenAPI schema. Do not edit.
 *
 * Regenerate with `pnpm gen-api-types` whenever a Pydantic model changes.
 * CI fails if this file has drifted, so a forgotten regeneration is caught at
 * the pull request rather than at runtime.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and boot state */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record frontend errors in the workspace log */
        post: operations["post_client_logs_api_v1_client_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only application settings and boot facts */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientLogAccepted */
        ClientLogAccepted: {
            /** Accepted */
            accepted: number;
        };
        /** ClientLogBatch */
        ClientLogBatch: {
            /** Entries */
            entries: components["schemas"]["ClientLogEntry"][];
        };
        /** ClientLogEntry */
        ClientLogEntry: {
            /**
             * Level
             * @enum {string}
             */
            level: "warn" | "error";
            /** Message */
            message: string;
            /**
             * Source
             * @description Which capture point produced it.
             */
            source: string;
            /** Stack */
            stack?: string | null;
            /** Route */
            route?: string | null;
            /**
             * Occurred At
             * @description ISO-8601 UTC from the client clock. Kept separate from the server timestamp the log line carries, because the two can disagree.
             */
            occurred_at?: string | null;
        };
        /**
         * HealthResponse
         * @description Everything the diagnostics screen needs from the backend side.
         */
        HealthResponse: {
            /**
             * Status
             * @description `degraded` means zero database sessions are being handed out — every DB-touching route returns 503. It does not mean 'available but flagged'.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Boot Id */
            boot_id: string;
            /** Backend Version */
            backend_version: string;
            /** App Version */
            app_version: string | null;
            /** Workspace Path */
            workspace_path: string;
            /** Boot Log Path */
            boot_log_path: string;
            /** Backend Log Path */
            backend_log_path: string;
            /** Migration Head */
            migration_head: string | null;
            /** Migration Current */
            migration_current: string | null;
            /** Backup Path */
            backup_path: string | null;
            /** Detail */
            detail: string | null;
            /** Started At */
            started_at: string;
        };
        /**
         * QualityPreset
         * @description DB.md §3.1 and §3.5.
         * @enum {string}
         */
        QualityPreset: "draft" | "standard" | "high";
        /**
         * SettingsResponse
         * @description DB.md §3.5, plus the boot facts Settings displays alongside them.
         */
        SettingsResponse: {
            quality_preset: components["schemas"]["QualityPreset"];
            /**
             * Encoder Override
             * @description NULL means auto-detect.
             */
            encoder_override: string | null;
            /** Default Export Path */
            default_export_path: string | null;
            /**
             * Ffmpeg Version
             * @description Cached probe result. NULL until P1 probes.
             */
            ffmpeg_version: string | null;
            /**
             * Detected Encoders
             * @description JSON array from the capability probe.
             */
            detected_encoders: string | null;
            /** Workspace Path */
            workspace_path: string;
            /** Backend Version */
            backend_version: string;
            /** App Version */
            app_version: string | null;
            /** Boot Id */
            boot_id: string;
            /** Migration Head */
            migration_head: string | null;
            /** Backend Log Path */
            backend_log_path: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ApiErrorCode
         * @description Why a *request* failed.
         *
         *     Q124: this is one of **two** enums and they never share a value. The other
         *     is the diagnostics code set in ``src-tauri/src/diagnostics.rs``, which
         *     describes why the *application* cannot run. Nothing is ever both, and the
         *     temptation to reach across arrives around P4 — hence the comment on each.
         * @enum {string}
         */
        ApiErrorCode: "validation_error" | "not_found" | "conflict" | "workspace_error" | "unauthorized" | "internal_error";
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ApiErrorCode"];
            /**
             * Message
             * @description Plain language, written for a user.
             */
            message: string;
            /**
             * Details
             * @default null
             */
            details: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_client_logs_api_v1_client_logs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientLogBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientLogAccepted"];
                };
            };
            /** @description Error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
